### PR TITLE
Improve hex encoding, use it in `kontrol show` by default

### PR DESCRIPTION
**Pull request by jinxinglim**
Merging of this PR will close issue https://github.com/runtimeverification/kontrol/issues/505.

This PR changes the default setting for `kontrol show` to use and display hex encoding and if the user does not want to use hex encoding, he/she can add the option `--no-use-hex-encoding`.

### Questions

1. Is the help message in this argument okay? Please feel free to suggest a better one. 
    ```python
        show_args.add_argument(
            '--no-use-hex-encoding',
            dest='use_hex_encoding',
            default=None,
            action='store_false',
            help='Print elements in non-hexadecimal encoding.',
        )
    ```

2. I changed the default `use_hex_encoding` in some of the function, e.g., `__init__` from `src/kontrol/foundry.py`, from `False` to `True` and I am not sure if it will affect its dependencies. From the CI failed tests, it seems like it is affecting its dependencies? Should I change them back to the default `False`?

Added by Palina on 25/07:

We're missing a few things: 
- leaving integer constants as they are, e.g., `32` instead of `0x1000000000000000000000000`;
- preserving aliases such as `maxUint256` 
- changing default values in functions back

### CODE REVIEW

**Comment by anvacaru** [comment]
One limitation of our current hex encoding is that aliases such as `maxUInt256` are no longer displayed in the CTerm. Only the hex value is displayed.

**Comment by jinxinglim** [comment]
> One limitation of our current hex encoding is that aliases such as `maxUInt256` are no longer displayed in the CTerm. Only the hex value is displayed.

@anvacaru Do you think this limitation should be fix in this PR? I am not too sure how easy/difficult this fix will be. If yes, could I trouble you to point me to files that I can work on? Thank you!

**Comment by anvacaru** [comment]
>@anvacaru Do you think this limitation should be fix in this PR?

No, that's out of the scope of this PR. I wanted to bring it up, as it could make the kcfg less readable in a way. @PetarMax, what do you think?

**Comment by palinatolmach** [comment]
We'll need to bring `True` as default value for `use_hex_encoding` and update the output before merging, but I agree that `0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff` is less readable than `maxUint256`, and I'm worried it'll interfere with the engagement. Good call @anvacaru, thanks! Let's probably postpone merging it for a few weeks or until we figure out how to continue using aliases?

**Comment by palinatolmach** [comment]
We're missing a few things: 
- leaving integer constants as they are, e.g., `32` instead of `0x1000000000000000000000000`;
- preserving aliases such as `maxUint256` 
- changing default values in functions back

**Comment by palinatolmach** [comment]
Closing for now, since we won't make hex encoding the default in `kontrol show` until it's improved. The list of improvements needed is available in https://github.com/runtimeverification/kontrol/issues/505.

**Pull request closed without merging**
