### PR TITLE
Stabilising produced EVM code

### PR DESCRIPTION
**Pull request by PetarMax**
This PR stabilises the EVM bytecode produced by the compiler by not including the IPFS hash and the CBOR metadata.

This is relevant, for example, for summary reusability in CSE.

### CODE REVIEW

**Review by anvacaru — APPROVED** [review]

**Comment by ehildenb** [comment]
If we're not sure that we want this turned on all teh time, let's make it a CLI flag that changes behavior based on that flag. Then we can choose dynamically if we want that logic.

**Comment by PetarMax** [comment]
It is turning out to be difficult to introduce this into the `forge build`
pipeline, since the required options would have to be passed to `solc`
directly.

**Comment by PetarMax** [comment]
Request to add desired functionality was made to the Foundry team [here](https://github.com/foundry-rs/foundry/issues/7488).

**Comment by palinatolmach** [comment]
`--no-metadata` has been added in Foundry: https://github.com/foundry-rs/foundry/pull/7684.

**Comment by palinatolmach** [comment]
Blocked on https://github.com/runtimeverification/kontrol/issues/525.

**Review by palinatolmach — APPROVED** [review]

**Pull request merged**
