### PR TITLE
Refactor digest checks.

### PR DESCRIPTION
**Pull request by anvacaru**
- Modified `update_kompilation_digest` to store the kontrol version in the digest file.
- Added a new `kontrol_up_to_date` function that checks if the current version is the same as the one in the digest file.
- Added a new `should_rekompile` function in `foundry_kompile` that: 
     - checks if there's an explicit request to recompile.
     - checks if the compilation timestamp file does not exist.
     - checks if any of the components (definitions, contracts, or tool) are not up to date.
- refactored all the `*up_to_date` and `update_digest` methods and extracted the common logic in a single  `_read_digest_file` function.
- Modified `resolve_proof_version` and `resolve_setup_proof_version` to check the kontrol verison using `kontrol_up_to_date`, emitting a warning if it is out of date.

### CODE REVIEW

**Comment by F-WRunTime** [comment]
Will the `kontrol_up_to_date` be a hard check for enforcing the version of kontrol defined in toml is what is used for the execution process? 

Will there be an option to make it a soft enforcement and just provides a warning instead of an error?

**Comment by F-WRunTime** [comment]
The above question may also be getting addressed in #725 ?

**Comment by anvacaru** [comment]
@F-WRunTime currently it isn't set to enforce the version of kontrol. For `kontrol build`, it will trigger a rekompilation. For `prove` it will only emit a warning, because the tool version might contain changes to the semantics and so the definition might become outdated.

**Review by palinatolmach — APPROVED** [review]
Looks really good to me, thanks @anvacaru!

I opened an issue about documenting the rekompilation/reinitialization logic for us to address whenever someone has time (https://github.com/runtimeverification/gitbook-kontrol/issues/54).

**Pull request merged**
